model_id: /root/autodl-tmp/Qwen2.5-Math-1.5B
train_jsonl: data/MATH/train.jsonl
val_jsonl: data/MATH/validation.jsonl
output_dir: runs/grpo_loop_test-1

n_grpo_steps: 200
learning_rate: 1e-5
advantage_eps: 1e-6

rollout_batch_size: 256
group_size: 8
sampling_temperature: 1.0
sampling_top_p: 1.0
sampling_min_tokens: 4
sampling_max_tokens: 1024

epochs_per_rollout_batch: 1
train_batch_size: 256
gradient_accumulation_steps: 128

vllm_gpu_memory_utilization: 0.75

# "no_baseline",
# "reinforce_with_baseline",
# "grpo_clip"
loss_type: reinforce_with_baseline
use_std_normalization: true

eval_every_grpo_steps: 10
eval_max_examples: 1024
eval_batch_size: 256
